[package]
name = "chess"
version = "0.1.0"
authors = ["Nico"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
shakmaty = "0.13.0"
chess = "2.0.2"
crossbeam = "0.7.1"
rayon = "1.0.3"
indicatif = "0.11.0"
clap = "2.32.0"
text_io = "0.1.7"