[package]
name = "chess"
version = "0.1.0"
authors = ["Nico"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
lazy_static = "1.2.0"
log = "0.4.6"
env_logger = "0.6.0"
shakmaty = "0.13.0"
crossbeam = "0.7.1"
rayon = "1.0.3"